### ISSUE TITLE
Variant-based co-occurrence analysis

### ISSUE THREAD

**Issue by zyh4482** [NKI-CCB/DISCOVER#17]
Thanks for your wonderful tool. 

I noticed that discover is designed for testing mutual exclusivity and co-occurrence of pairwised genes. 

If I have two variants within the same gene, can I use discover to test their co-occurence? Obviously, variant distribution is not identical. What I'm trying to do does not violate the prerequisite, is that correct? 

In such case, how should I create the background discover.matrix? Maybe create a matrix containing all variants in that gene? 

Thank you.

**Comment by scanisius** [comment]
You are right that DISCOVER has primarily been developed with the objective of testing at the gene-level. That being said, you may be able to stretch this up to other units. There are a couple of things to keep in mind.

- DISCOVER's background model will probably lose power if you try to fit it to very sparse data. So I would not create a matrix with individual mutations in the rows, since this will probably lead to very few mutations for all but the most obvious hotspots. Depending on your particular research question you might consider taking protein domains as the unit in the rows of the matrix.
- An assumption of the DISCOVER model is that most of the mutations in your matrix are passenger mutations. So when creating the input matrix it is important that you do not only use mutations in your gene of interest, but preferably mutations in genes all across the genome. If you don't have whole-exome mutation data, gene-panel data for a few hundred genes will also work.
- Taking these considerations into account, you will probably be able to perform your analysis. However, we have not tested this situation ourselves, so make sure you have a critical look at the results you obtain.
